blog/config/routes.rb
Rails.application.routes.draw do
  resources :comments

  devise_for :users
  get 'bienvenido/accion1'

  get "bienvenido", to: "bienvenido#accion1"

  resources :articles

   root 'welcome#index'

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true,  uniqueness: true
	validates :body, presence: true, length: {minimum: 20}

	before_create :set_visits_count

	def update_visit_count
		self.update(visit_count: self.visit_count + 1)
	end


	private

	def set_visits_count
		self.visit_count = 0
	end
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:show, :index] 
	before_action :set_article, except: [:index, :new, :create]
	#GET /articles
	#Lista de todos los artículos
	def index
		@articles = Article.all
	end

	#GET /articles/:id
	#Muestra el artículo que queremos ver, pasando el id
	def show
		@article.update_visit_count
	end

	#GET /articles/new
	#Creamos un artículo
	def new
		@article = Article.new
	end

	#POST /articles
	def create
		@article = current_user.articles.new(article_params)

		if @article.save
			redirect_to @article
		else
			render :new
		end

	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end

	#GET /articles/:id/edit
	def edit
		
	end

	
	def update
		if @article.update(article_params)
			redirect_to @article
		else
			render :edit
		end
	end

	#Filtrado de parametros para create

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :body)
	end 

end

blog/app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def accion1
  end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    respond_with(@comment)
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_form.html.erb
<h1><%= name %> Artículo</h1>

<%= form_for(@article) do |f| %>
	<% @article.errors.full_messages.each do |message| %>
		<div class = "be-red white top-space">
			<%= message %>
		</div>
	<%end%>
	
	<div class = "field">
		<%= f.text_field :title, placeholder: "Título" , class: "form-control"%>
	</div>
	
	<div>
		<%= f.text_area :body, placeholder: "Escribe aquí", style: "height: 250px;", class: "form-control" %>
	</div>

	<div class="field">
		<%= f.submit "Guardar", class: "btn be-red white" %>
	</div>
<% end %>

blog/app/views/articles/edit.html.erb
<div style="width:80%; margin:0 auto;">
	<%= render "form" , name: "Editar"%>
</div>

blog/app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<h1><%= link_to article.title, article %></h1>
	<div>
		<%= article.body %> --> <%= link_to "Eliminar", article, method: :delete %>
	</div>
<%end%>

blog/app/views/articles/new.html.erb
<div style="width:80%; margin:0 auto;">
	<%= render "form" , name: "Crear"%>
</div>

blog/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<%unless @article.user.nil? %>
<p>
	Escrito por: <%= @article.user.email %>
</p>
<%end%>

<p>
	Número de visitas: <%= @article.visit_count %>
</p>

<div>
	<%= @article.body %>
</div>

<div>
	<%= link_to "Editar", edit_article_path(@article)%>
	<%= link_to "Regresar", articles_path%>
</div>

blog/app/views/bienvenido/accion1.html.erb
<h1>Ejecutando código de Ruby</h1>

<h2>Sin el igual</h2>

<% [1,2,3,4,5].each do |num| %>
	<p>Número: <%= num %></p>
<%end%>

<h2>Con el igual</h2>

<%= [1,2,3,4,5].each do |num| %>
	<p>Número: <%= num %></p>
<%end%>

<p>El arreglo también se imprimió en la pantalla porque tenía en el boque de código un igual.</p>

blog/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.text_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

blog/app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

blog/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

blog/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <link href='https://fonts.googleapis.com/css?family=Inconsolata:700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "partials/navigation" %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

blog/app/views/partials/_navigation.html.erb
<header>
	<nav class = "be-red white large-padding">
		<ul class = "no-list row center-xs middle-xs">
			<li class="col-md">
				<h1 class="no-margin">Ruby PROTECO</h1>
			</li >
			<li class="col-md">
				<%= link_to "Inicio", root_path %>
			</li>
			<li class="col-md">
				<%= link_to "Artículos", articles_path%>
			</li>
			<li class="col-md">
				<%= link_to "Crear artículo", new_article_path(@article)%>
			</li>
			<li class="col-md">
				<%= link_to "Vista extra", bienvenido_path %>
			</li>

			<%if user_signed_in? %>
				<li class = "col-md">
					<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete%>
				</li>
			<%else%>
				<li class = "col-md">
					<%= link_to "Iniciar Sesión", new_user_session_path%>
				</li>
				<li class = "col-md">
					<%= link_to "Crear Cuenta" ,new_user_registration_path%>
				</li>
			<%end%>

		</ul>
	</nav>
</header>

blog/app/views/welcome/index.html.erb
<% if user_signed_in? %>
	<h1>Hola <%= current_user.email%></h1>
<%else %>
	<h1>Bienvenido al blog de PROTECO</h1>
<%end %>